export const DEFAULT_PUBLICATIONS = [
  {
    hash: 'QmXKShp8tQd8jmFD5bQzJNeoDL3CUWgoSbYrueJHSiHoTh',
    caption: 'Create New GIF',
    path: '/onboarding-gifs/create-new-gif.gif',
    nickname: 'Thicket',
  },
  {
    hash: 'QmSPJAfNidu4ofwhApeRneYeqpoBoJURWHaopvBnEV6GGp',
    caption: 'Share Your Community',
    path: '/onboarding-gifs/share-your-community.gif',
    nickname: 'Thicket',
  },
  {
    hash: 'QmRTooGFkG19BZMuUXoXYDMKLkeaTXxohPDErcGea9YrD2',
    caption: 'Welcome to Thicket',
    path: '/onboarding-gifs/welcome-to-thicket.gif',
    nickname: 'Thicket',
  },
]
export const PLACEHOLDER = '/images/placeholder.png'
export const COMMUNITY_NAMES = [
  'Fast scooter',
  'Angry rooster',
  'Happy pig',
  'Coral couches',
  'Orchid vase',
  'Burgundy house',
  'Blue ocean',
  'Circle patterns',
  'Palm tree',
  'Mango fruit',
  'Watermelon snacks',
  'Tea cups',
  'Coconut drinks',
  'Chocolate bars',
  'Vietnamese subs',
  'Fresh lettuce',
  'Peeled carrot',
  'Olive soap',
  'Sun shining ',
  'Beach days',
  'Where have all the cowboys gone?',
  'Peachy whales',
  'Enchanted',
  'Poisson is french for fish',
  'These GIFs where created equally',
  'Rock of Gibraltar',
  'A muse',
  'Rockaway',
  'November mist',
  'Turtle dove',
  'Rick & Morty’s',
  'Art museum',
  'This is what’s left of civilization',
  'Holiday aramadillo',
  'Down to earth GIFs',
  'Closing time',
  'New furniture',
  'Augmented reality',
  'Cats, cats, cats...',
  'Home is where the GIFs are',
  'Kitchen sink',
]
export const TIMEOUT = 120000
